service:
  internalPort: 80
  externalPort: 80

ingress:
  enabled: true
  tls:
    enabled: true
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
